[
 {"alumno":"Jimmy","nota":10.00,"ranking":1},
 {"alumno":"Juan2","nota":4,"ranking":100},
 {"alumno":"Juan3","nota":5,"ranking":20},
 {"alumno":"Juan4","nota":9.09,"ranking":21},
 {"alumno":"Juan5","nota":8.3,"ranking":15},
 {"alumno":"Juan6","nota":1,"ranking":12},
 {"alumno":"Juan7","nota":9.9,"ranking":8},
 {"alumno":"Juan8","nota":4.5,"ranking":19},
 {"alumno":"Juan9","nota":7,"ranking":3},
 {"alumno":"Molina","nota":10,"ranking":2}
]